project 'mc6_2019_hackathon.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mc6_2019_hackathon' do
  pod 'SwiftSocket', '~> 2.0'
  use_frameworks!

  # Pods for mc6_2019_hackathon

end
